version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fishek-postgres
    environment:
      POSTGRES_DB: fishek_db
      POSTGRES_USER: fishek
      POSTGRES_PASSWORD: fishek
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fishek-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fishek.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
